In [1]:
import torch

X = torch.randn(4, 5)

# Batch Normalization
batch_mean = X.mean(dim=0, keepdim=True)
batch_var = X.var(dim=0, unbiased=False, keepdim=True)

batch_norm = (
    X - batch_mean
) / torch.sqrt(batch_var + 1e-5)

# Layer Normalization
layer_mean = X.mean(dim=1, keepdim=True)
layer_var = X.var(dim=1, unbiased=False, keepdim=True)

layer_norm = (
    X - layer_mean
) / torch.sqrt(layer_var + 1e-5)

print("Input:")
print(X)

print("\nBatch Normalization:")
print(batch_norm)

print("\nLayer Normalization:")
print(layer_norm)

Input:
tensor([[-0.3845,  2.2359,  1.2269,  0.5547, -3.9306],
        [ 1.4760,  0.2930, -0.1118,  0.7418,  1.5873],
        [ 0.8373, -1.5478, -0.7796,  0.7624, -0.3690],
        [ 0.2697, -0.5509, -1.9092, -0.5047, -0.2735]])

Batch Normalization:
tensor([[-1.3583,  1.5302,  1.4278,  0.3183, -1.5945],
        [ 1.3470,  0.1333,  0.2482,  0.6767,  1.1686],
        [ 0.4183, -1.1902, -0.3403,  0.7161,  0.1890],
        [-0.4070, -0.4734, -1.3357, -1.7111,  0.2368]])

Layer Normalization:
tensor([[-0.1536,  1.0847,  0.6079,  0.2902, -1.8292],
        [ 1.0306, -0.7657, -1.3803, -0.0843,  1.1996],
        [ 1.1555, -1.4527, -0.6126,  1.0735, -0.1636],
        [ 1.2001,  0.0595, -1.8283,  0.1237,  0.4451]])
